# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
      hostname: mongodb
      image: mongodb/mongodb-atlas-local
      enviroment:
        - MONGODB_INITDB_ROOT_USERNAME=user
        - MONGODB_INITDB_ROOT_PASSWORD=pass
        - RUNNER_LOG_FILE=/dev/stderr
      ports:
        - 27018:27017
      volumes:
        - ./init:/docker-entrypoint-initdb.d
        - ${PWD}/upload/restaurants.json:/tmp/restaurants.json

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false

  jupyter:
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
    
  # ollama: 
  #   image: ollama/ollama
  #   volumes: 
  #     - ./ollama-models:/root/.ollama
  #   ports:
  #     - 11434:11434

  # web:
  #   image: nginx:1.27.3-alpine
  #   volumes:
  #     - ./web:/usr/share/nginx/html
  #   ports:
  #     - "3001:80"